<div class="Promo">
	<div class="container pt-4 pb-4">
		<div class="row">
			<div class="col-12">
				<?php
					if($element->HasTitle())
					echo '<h2>', $element->GetTitle(), '</h2>', PHP_EOL;
				?>
				<?php
					if($element->HasSubtitle())
					foreach(explode("\n",$element->GetSubtitle()) as $Line)
					echo '<p>', $Line, '</p>';

					echo PHP_EOL;
				?>
			</div>
		</div>
	</div>
</div>
