<?php

$Builder = new class {

	public function
	Print($Object):
	?String {

		if($Object instanceof Atlantis\Item)
		return $this->PrintFromItem($Object);

		return NULL;
	}

	public function
	PrintFromItem(Atlantis\Item $Item):
	String{

		$Post = $Item->GetObject();
		$Blog = $Post->GetBlogObject();
		$HTML = new Atlantis\Util\ZenHTML('
			div[id=`ItemID` class=`ItemClass`]
				>(
					h1
					>a[href=`PostURL`]{`PostTitle`}
				)
				+(div>(
					{From }
					+a[href=`BlogURL`]{`BlogTitle`}
					+{ On }
					+em{`PostDate`}
				))
		');

		return $HTML->Create([
			'ItemID'    => $Item->GetID(),
			'ItemClass' => $Item->GetClassesAttrString(),
			'PostTitle' => $Post->GetTitle(),
			'PostURL'   => $Post->GetURL(),
			'PostDate'  => $Post->GetDateTimePosted(),
			'BlogTitle' => $Blog->GetTitle(),
			'BlogURL'   => $Blog->GetURL()
		]);
	}

};

?>

<div class="Atlantis-Element Atlantis-Element-PostListing">
	<?php if($element->HasTitle()): ?><legend><?php echo htmlentities($element->GetTitle()) ?></legend><hr class="MarginBelowNormal" /><?php endif; ?>
	<?php foreach($element->GetItems() as $Item) echo $Builder->Print($Item); ?>
</div>
