<?php

/**
 * @var Atlantis\Struct\SearchResult $Blogs
 * @var Atlantis\Prototype\Blog $BlogUser
 * */

?>

<?php $Surface->Area('dashboard/promo') ?>

<div class="container">
	<div class="row">
		<div class="col-md-8 mb-6">
			<h2>Your Blogs</h2>
			<?php foreach($Blogs->Payload as $Blog): ?>
			<div class="row align-items-center tight mb-2">
				<div class="col-auto">
					<a href="<?php echo $Blog->Blog->URL ?>" class="font-size-large font-weight-bold"><?php echo $Blog->Blog->Title ?></a>
				</div>
				<div class="col">
				</div>
				<div class="col-auto">
					<a href="<?php echo $Endpoint('Atlantis.Dashboard.Blog.Post',['BlogID'=>$Blog->Blog->ID]) ?>" class="btn btn-dark text-uppercase"><i class="fa fa-fw fa-edit"></i></a>
				</div>
				<div class="col-auto">
					<a href="<?php echo $Endpoint('Atlantis.Dashboard.Blog.Settings',['BlogID'=>$Blog->Blog->ID]) ?>" class="btn btn-dark text-uppercase"><i class="fa fa-fw fa-wrench"></i></a>
				</div>
			</div>
			<?php endforeach; ?>
			<?php if(!$Blogs->Total): ?>
			<div class="p-4 text-center">
				You have not created any blogs yet.
			</div>
			<?php endif; ?>
		</div>
		<div class="col-md-4 mb-6">
			<h2>Blogging</h2>
			<a href="<?php echo Atlantis\Site\Endpoint::Get('Atlantis.Dashboard.Blog.Create') ?>" class="btn btn-secondary btn-block text-left"><i class="fa fa-fw mr-1 fa-plus-square"></i> Create New Blog</a>
			<hr class="border-0 mt-6 mb-6" />
			<h2>Account</h2>
			<a href="" class="btn btn-dark btn-block text-left"><i class="fa fa-fw mr-1 fa-at"></i> Change Email</a>
			<a href="" class="btn btn-dark btn-block text-left"><i class="fa fa-fw mr-1 fa-key"></i> Change Password</a>
		</div>
	</div>

</div>
