
<?php $Surface->Area('dashboard/promo') ?>

<div class="container pb-4">

	<ol class="breadcrumb mb-6">
		<li class="breadcrumb-item"><a href="<?php echo Atlantis\Site\Endpoint::Get('Atlantis.Dashboard.Home') ?>">Dashboard</a></li>
		<li class="breadcrumb-item">Account</li>
		<li class="breadcrumb-item active">Change Password</li>
	</ol>

	<!-- PASSWORD -->
	<div id="UserPassword" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Change Password</h2>
			<hr class="mb-2 mt-2" />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword0" type="password" autocomplete="off" class="form-control" placeholder="Old Password..." />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword1" type="password" autocomplete="off" class="form-control" placeholder="New Password..." />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword2" type="password" autocomplete="off" class="form-control" placeholder="Confirm Password..." />
		</div>
		<div class="col-12"></div>
		<div class="col-auto mb-2">
			<butt type="button" class="btn btn-block btn-dark ActionCommit">Update Password</button>
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">
jQuery(document)
.ready(function(){
	let Password = new Atlantis.Action.StatusHandler({
		'Element': '#UserPassword',
		'OnCommit': function(Handler){
			let Password0 = jQuery('#InputPassword0').val();
			let Password1 = jQuery('#InputPassword1').val();
			let Password2 = jQuery('#InputPassword2').val();

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/user/entity',
				'Data': { 'Fields': { 'Password0':Password0, 'Password1':Password1, 'Password2':Password2 } },
				'OnSuccess': function(Result){
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Account Settings',
						'Content': 'Your password has been updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Account Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	return;
});
</script>
