<?php

/**
 * @var Atlantis\Prototype\User $User
 */

$Surface->Area('dashboard/promo');

?>

<div class="container pb-4">

	<ol class="breadcrumb mb-6">
		<li class="breadcrumb-item"><a href="<?php echo Atlantis\Site\Endpoint::Get('Atlantis.Dashboard.Home') ?>">Dashboard</a></li>
		<li class="breadcrumb-item">Account</li>
		<li class="breadcrumb-item active">Change Password</li>
	</ol>

	<!-- PASSWORD -->
	<div id="UserPassword" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Change Password</h2>
			<hr class="mb-2 mt-2" />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword0" type="password" autocomplete="off" class="form-control" placeholder="Old Password..." />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword1" type="password" autocomplete="off" class="form-control" placeholder="New Password..." />
		</div>
		<div class="col-12 mb-2">
			<input id="InputPassword2" type="password" autocomplete="off" class="form-control" placeholder="Confirm Password..." />
		</div>
		<div class="col-12"></div>
		<div class="col-auto mb-2">
			<butt type="button" class="btn btn-block btn-dark ActionCommit">Update Password</button>
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<?php if($User->UsesThirdPartyAuth()): ?>
		<div class="col-12 pt-4">
			<div class="quotron quotron-secondary text-muted font-italic">
				Note: if your account was created logging in with a third-party service it has
				no password. If you would like to add a password in the event you get locked
				out of the service you used click here to start the "forgot my password" process
				to confirm your email and set a new password.
			</div>
		</div>
		<?php endif; ?>
	</div>

	<div class="row mb-6">
		<div class="col-12 mb-4">
			<h2 class="font-size-large font-weight-bold">Third Party Auth</h2>
			<hr class="mb-2 mt-2" />
		</div>
		<div class="col-12 mb-4">
			<div class="quotron quotron-primary border-color-github pt-4 pb-4 font-size-largerer font-weight-bold">
				<div class="row align-items-center">
					<div class="col-auto">
						<i class="fab fa-fw fa-github font-size-largerer"></i>
					</div>
					<div class="col">
						Github
						<?php if($User->AuthGithubID): ?><div class="text-muted font-size-small text-italic font-weight-normal">ID: <?php $Printer($User->AuthGithubID) ?></div><?php endif; ?>
					</div>
					<div class="col-auto">
						<?php if($User->AuthGithubID): ?>
						<button class="btn btn-dark"><i class="fas fa-fw fa-check text-success"></i> Connected</button>
						<?php else: ?>
						<button class="btn btn-dark"><i class="fas fa-fw fa-check text-success"></i> Connected</button>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
		<div class="col-12 mb-4">
			<div class="quotron quotron-primary border-color-twitter pt-4 pb-4 font-size-largerer font-weight-bold">
				<div class="row align-items-center">
					<div class="col-auto">
						<i class="fab fa-fw fa-twitter font-size-largerer"></i>
					</div>
					<div class="col">
						Twitter
						<?php if($User->AuthTwitterID): ?><div class="text-muted font-size-small text-italic font-weight-normal">ID: <?php $Printer($User->AuthTwitterID) ?></div><?php endif; ?>
					</div>
					<div class="col-auto">
						<?php if($User->AuthTwitterID): ?>
						<button class="btn btn-dark"><i class="fas fa-fw fa-check text-success"></i> Connected</button>
						<?php else: ?>
						<button class="btn btn-dark"><i class="fas fa-fw fa-times text-danger"></i> Not Connected</button>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">
jQuery(document)
.ready(function(){
	let Password = new Atlantis.Action.StatusHandler({
		'Element': '#UserPassword',
		'OnCommit': function(Handler){
			let Password0 = jQuery('#InputPassword0').val();
			let Password1 = jQuery('#InputPassword1').val();
			let Password2 = jQuery('#InputPassword2').val();

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/user/entity',
				'Data': { 'Fields': { 'Password0':Password0, 'Password1':Password1, 'Password2':Password2 } },
				'OnSuccess': function(Result){
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Account Settings',
						'Content': 'Your password has been updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Account Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	return;
});
</script>
