<?php

/**
 * @var Atlantis\Element\PostListing $Element
 * @var Atlantis\Datastore $Blogs
 * @var Atlantis\Prototype\Blog $Blog
 */

$Blogs = $Element->GetItemStore();

?>

<div class="PostListing <?php echo $Element->GetClassesAttrString() ?>">
	<h2><?php echo $Element->GetTitle() ?></h2>
	<?php foreach($Blogs as $Blog): ?>
	<div class="Post">
		<h3><a href="<?php $Printer($Blog->GetURL()) ?>"><?php $Printer($Blog->Title) ?></a></h3>
		<div class="About">
		</div>
	</div>
	<?php endforeach; ?>
	<?php if(!$Blogs->Count()): ?>
	<div class="text-center font-style-italic">
		There is nothing to see here.
	</div>
	<?php endif; ?>
</div>
