<?php

/**
 * @var Atlantis\Element\PagePromo $Element
 */

$Title = '';
$Subtitle = '';
$Image = NULL;
$Icon = NULL;

////////

if($Element->HasURL())
$Title = sprintf('<h2><a href="%s">%s</a></h2>',$Element->GetURL(),$Element->GetTitle());

elseif($Element->HasTitle())
$Title = sprintf('<h2>%s</h2>',$Element->GetTitle());

if($Element->HasSubtitle())
$Subtitle = sprintf('<p>%s</p>',$Element->GetSubtitle());

if($Element->HasImageURL())
$Image = sprintf('background-image:url(%s);',$Element->GetImageURL());

if($Element->HasIconURL())
$Icon = $Element->GetIconURL();

?>

<div class="Promo <?php echo $Element->GetClassesAttrString() ?>">
	<div class="PromoWash" style="<?php echo $Image ?>"></div>
		<div class="PromoContain container">
			<div class="p-4" style="box-shadow:0px 0px 24px #000; background-size:cover;background-position:center center;<?php echo $Image ?>">
				<div class="row align-items-center">
					<?php if($Icon): ?>
					<div class="d-none d-sm-block col-12 col-sm-3 col-md-2 mb-4 mb-sm-0">
						<div class="ImageIcon WallpaperedBox Square rounded" style="background-image:url(<?php echo $Icon ?>);"><a href="<?php echo $Element->GetURL() ?>"></a></div>
					</div>
					<?php endif; ?>
					<div class="col">
						<?php echo $Title, $Subtitle, PHP_EOL ?>
						<?php if($Element->HasFeedURL()): ?>
						<div>
							<a href="<?php echo $Element->GetFeedURL() ?>" class="d-inline-block font-size-mostest-small" style="margin:0px;padding:0px;">
								<span class="fa-stack fa-2x d-inline-block" style="margin-left:-4px;">
									<i class="fas fa-square fa-stack-2x text-rss"></i>
									<i class="fas fa-rss fa-stack-1x text-white"></i>
								</span>
							</a>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
