<?php

/**
 * @var Atlantis\Element\PagePromo $Element
 */

$Title = '';
$Subtitle = '';

////////

if($Element->HasURL())
$Title = sprintf('<h2><a href="%s">%s</a></h2>',$Element->GetURL(),$Element->GetTitle());

elseif($Element->HasTitle())
$Title = sprintf('<h2>%s</h2>',$Element->GetTitle());

////////

if($Element->HasSubtitle())
$Subtitle = sprintf('<p>%s</p>',$Element->GetSubtitle());

?>

<div class="Promo">
	<div class="container pt-4 pb-4">
		<div class="row">
			<div class="col-12">
				<?php echo $Title, $Subtitle, PHP_EOL ?>
			</div>
		</div>
	</div>
</div>
