<?php

/**
 * @var Atlantis\Element\PostListing $Element
 * @var Atlantis\Datastore $Posts
 * @var Atlantis\Prototype\BlogPost $Post
 */

$Posts = $Element->GetItemStore();

?>

<div class="PostListing <?php echo $Element->GetClassesAttrString() ?>">
	<h2><?php echo $Element->GetTitle() ?></h2>
	<?php foreach($Posts as $Post): ?>
	<div class="Post">
		<h3><a href="<?php echo $Post->GetURL() ?>"><?php echo Atlantis\Util\Filters::SafeForHTML($Post->Title) ?></a></h3>
		<div class="About">
			Posted on <a class="Date" href="<?php echo $Post->URL ?>"><?php echo $Post->DateCreated->Format('F jS g:ia') ?></a>
			From <a class="Source" href="<?php echo $Post->Blog->URL ?>"><?php echo $Post->Blog->Title ?></a>
			By <a class="Authour" href="<?php echo $Post->User->URL ?>"><?php echo $Post->User->Alias ?></a>
		</div>
	</div>
	<?php endforeach; ?>
	<?php if(!$Posts->Count()): ?>
	<div class="p-4 text-center">
		No posts here yet.
	</div>
	<?php endif; ?>
</div>
