<?php

/**
 * @var Atlantis\Element\PostListing $Element
 * @var Atlantis\Datastore $Posts
 * @var Atlantis\Prototype\BlogPost $Post
 */

$Posts = $Element->GetItemStore();

$PrintPostDetails = function(Atlantis\Prototype\BlogPost $Post) {

	$Infos = [];
	$Minutes = 0;

	if($Post->CountComments)
	$Infos[] = sprintf(
		'<i class="fas fa-fw fa-comment"></i> %s %s',
		$Post->CountComments,
		Atlantis\Util::IfOneOrNot($Post->CountComments,'Comment','Comments')
	);

	if($Post->CountImages)
	$Infos[] = sprintf(
		'<i class="fas fa-fw fa-image"></i> %s %s',
		$Post->CountImages,
		Atlantis\Util::IfOneOrNot($Post->CountImages,'Image','Images')
	);

	if($Post->CountCodeBlocks)
	$Infos[] = sprintf(
		'<i class="fas fa-fw fa-code"></i> %s %s',
		$Post->CountCodeBlocks,
		Atlantis\Util::IfOneOrNot($Post->CountCodeBlocks,'Code Block','Code Blocks')
	);

	if($Minutes = $Post->GetMinutesToRead())
	$Infos[] = sprintf(
		'<i class="fas fa-fw fa-clock"></i> %s Min Read',
		$Minutes
	);

	if($Post->Blog->Session->HasEditPriv())
	$Infos[] = sprintf(
		'<i class="fas fa-fw fa-eye"></i> %d Views',
		$Post->CountViews
	);

	return join(' | ',$Infos);
};

?>

<div class="PostListing HideTheLastHr <?php echo $Element->GetClassesAttrString() ?>">

	<div class="row align-items-center">
		<div class="col">
			<h2>
				<?php echo $Element->GetTitle() ?>
				<?php if($Element->HasSubtitle()): ?>
				<div class="letter-space-barely font-weight-normal font-size-smaller opacity-75 mb-2"><?php echo $Element->GetSubtitle() ?></div>
				<?php endif; ?>
			</h2>
		</div>
		<?php if($Element->HasFeedURL()): ?>
		<div class="col-auto">
			<a href="<?php echo $Element->GetFeedURL() ?>" target="_blank" class="btn btn-rss btn-sm btn-hover-reveal font-size-smaller"><i class="fas fa-fw fa-rss"></i><span class="ml-1 reveal">RSS</span></a>
		</div>
		<?php endif; ?>
	</div>

	<hr class="mt-2 mb-4" />
	<?php foreach($Posts as $Post): /** @var Atlantis\Prototype\BlogPost $Post */ ?>
	<div class="Post <?php echo $Post->GetStyleClassAttr() ?>">

		<div class="row align-items-top">
			<div class="col-12">
				<div class="row">
					<div class="col-12 mt-0">
						<div><a class="text-decoration-none" href="<?php echo $Post->URL ?>"><?php echo $Post->DateCreated->Fancy() ?></a></div>
					</div>
					<div class="col-12 mt-2">
						<h3 class="d-flex align-items-center">
							<?php if($Post->IsDraft()): ?>
							<i class="flex-grow-0 fas fa-fw fa-sticky-note font-size-smallerer mr-1 HasTooltip" title="Draft"></i>
							<?php elseif($Post->IsPublic()): ?>
							<?php elseif($Post->IsFriendsOnly()): ?>
							<span class="fa-stack fa-2x mr-1 HasTooltip" title="Friends Only">
								<i class="fas fa-fw fa-square fa-stack-2x"></i>
								<i class="fas fa-fw fa-user-friends fa-stack-1x fa-inverse"></i>
							</span>
							<?php elseif($Post->IsNuked()): ?>
							<span class="fa-stack fa-2x mr-1 HasTooltip" title="Nuked">
								<i class="fas fa-fw fa-square fa-stack-2x"></i>
								<i class="fas fa-fw fa-radiation fa-stack-1x fa-inverse"></i>
							</span>
							<?php endif; ?>
							<?php if($Post->IsAdult()): ?>
							<i class="flex-grow-0 fas fa-fw fa-exclamation-square font-size-smallerer text-adult mr-1 HasTooltip" title="Adult Content"></i>
							<?php endif; ?>
							<a class="flex-grow-0" href="<?php echo $Post->GetURL() ?>"><?php echo Atlantis\Util\Filters::SafeForHTML($Post->Title) ?></a>
						</h3>
						<div class="row tight align-items-center line-height-0">
							<?php if(is_iterable($Post->Tags) && count($Post->Tags)): ?>
							<div class="col-auto">
								<?php foreach($Post->Tags as $Tag): ?>
								<a href="<?php $Printer($Post->Blog->GetTagURL($Tag)) ?>" class="btn btn-sm btn-outline-dark pt-0 pb-0 m-0"><?php $Printer($Tag->Title) ?></a>
								<?php endforeach; ?>
							</div>
							<?php endif ?>
						</div>
					</div>

					<?php if($Element->ShowPostPreview()): ?>
					<?php if($Post->Image): ?>
					<?php if($Element->ShowPostImage() === 1): ?>
					<div class="col-12 mt-4">
						<a href="<?php $Printer($Post->URL) ?>"><img src="<?php $Printer($Post->Image->GetURL('md')) ?>" class="rounded mw-100" /></a>
					</div>
					<?php endif; ?>
					<?php if($Element->ShowPostImage() === 2): ?>
					<div class="col-12 mt-4">
						<a href="<?php $Printer($Post->URL) ?>">
							<div class="PostPreviewFader">
								<img src="<?php $Printer($Post->Image->GetURL('md')) ?>" class="rounded mw-100" />
							</div>
						</a>
					</div>
					<?php endif; ?>
					<?php endif; ?>

					<div class="col-12 mt-3">
						<div class="font-family-reading"><?php echo $Desc = $Post->GetShortDesc() ?></div>

						<?php if($Desc): ?>
						<a class="d-block mt-2 font-weight-bold" href="<?php $Printer($Post->URL) ?>">Continue Reading...</a>
						<?php endif; ?>
					</div>
					<?php endif; ?>

					<?php if($Element->ShowSourceBlog()): ?>
					<div class="col-12 mt-3">
						<div class="opacity-75 font-size-smaller">
							From <a class="Source font-weight-light" href="<?php echo $Post->Blog->URL ?>"><?php echo $Post->Blog->Title ?></a>
							By <a class="Authour font-weight-light" href="<?php echo $Post->User->URL ?>"><?php echo $Post->User->Alias ?></a>
						</div>
					</div>
					<?php endif; ?>
					<div class="col-12 mt-2">
						<div class="opacity-75 font-size-smaller">
							<?php echo $PrintPostDetails($Post) ?>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
	<hr class="mt-4 mb-4" />
	<?php endforeach; ?>

	<?php if(!$Posts->Count()): ?>
	<div class="p-4 text-center">
		<div class="mb-4">This blog has no posts yet.</div>
		<div class="font-weight-bold font-size-larger"><?php $Printer(Atlantis\Util\Emote::Random('angry')) ?></div>
	</div>
	<hr class="mt-4 mb-4" />
	<?php endif; ?>
</div>
