<?php

/**
 * @var Atlantis\Element\PostListing $Element
 * @var Atlantis\Prototype\BlogPost $Post
 */

?>

<div class="PostListing <?php echo $Element->GetClassesAttrString() ?>">
	<h2 class="font-size-normal">
		<?php echo $Element->GetTitle() ?>
		<?php if($Element->HasSubtitle()): ?>
		<div class="letter-space-barely font-weight-normal font-size-smaller opacity-75 mb-2"><?php echo $Element->GetSubtitle() ?></div>
		<?php endif; ?>
	</h2>
	<?php foreach($Element->GetItemStore() as $Post): ?>
	<div class="Post">
		<div class="About">
			<span class="font-size-small"><?php echo $Post->DateCreated->Format('F jS g:ia') ?></span>
		</div>
		<h3 class="d-flex font-size-larger align-items-center">
			<?php if($Post->IsAdult()): ?>
			<i class="flex-grow-0 fa fas fa-exclamation-square font-size-smallerer text-adult mr-2 HasTooltip" title="This post contains Adult Content"></i>
			<?php endif; ?>
			<a class="flex-grow-0" href="<?php echo $Post->GetURL() ?>"><?php echo Atlantis\Util\Filters::SafeForHTML($Post->Title) ?></a>
		</h3>
	</div>
	<?php endforeach; ?>
</div>
