<div class="TwoCol1x3 <?php echo $element->GetClassesAttrString() ?>">
	<div>

<!-- sidebar content -->
<?php $element->Sidebar->Each(function($Element){
	echo $Element, PHP_EOL;
}) ?>
<!-- end sidebar content -->

	</div>
	<div>

<!-- start primary content -->
<?php $element->Main->Each(function($Element){
	echo "<main>", PHP_EOL;
	echo $Element, PHP_EOL;
	echo "</main>", PHP_EOL;
}) ?>
<!-- end primary content -->

	</div>
	<hr class="FloatClear" />
</div>