<?php

/**
 * @var Atlantis\Struct\SearchResult $BlogsRecent
 * @var Atlantis\Struct\SearchResult $PostsRecent
 * @var Atlantis\Struct\SearchResult $PostsPopular
 * @var Atlantis\Struct\SearchResult $UsersRecent
 * @var Atlantis\Prototype\User $User
 */

echo (new Atlantis\Element\PagePromo)
->SetTitle('Operations')
->SetSubtitle('Look, I\'m not asking you swim out there! I\'m asking you to push a few buttons!');

?>

<div class="container">

	<div class="row">
		<div class="col">
			<div class="row">
				<div class="col-12 mb-6">
					<h2>Popular Posts (30D)</h2>
					<hr />
					<?php foreach($PostsPopular->Payload as $Post): ?>
					<div>
						<div class="font-size-smaller text-muted">
							From <a href="<?php $Printer($Post->Post->Blog->URL) ?>" target="_blank"><?php $Printer($Post->Post->Blog->Title) ?></a>
							On <b><?php $Printer($Post->Post->DateCreated->Fancy()) ?></b>
						</div>
						<div class="font-size-large font-weight-bold"><a href="<?php $Printer($Post->Post->URL) ?>" target="_blank"><?php $Printer($Post->Post->Title) ?></a></div>
						<div>
							<?php $Printer($Post->Views) ?> Views (<?php $Printer($Post->Post->CountViews) ?> Total)
						</div>
					</div>
					<hr />
					<?php endforeach; ?>
				</div>
				<div class="col-12 mb-6">
					<h2>Newest Posts</h2>
					<hr />
					<?php foreach($PostsRecent->Payload as $Post): ?>
					<div>
						<div class="font-size-smaller text-muted">
							From <a href="<?php $Printer($Post->Blog->URL) ?>" target="_blank"><?php $Printer($Post->Blog->Title) ?></a>
							On <b><?php $Printer($Post->DateCreated->Fancy()) ?></b>
						</div>
						<div class="font-size-large font-weight-bold"><a href="<?php $Printer($Post->URL) ?>" target="_blank"><?php $Printer($Post->Title) ?></a></div>
					</div>
					<hr />
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div class="col-4">
			<div class="quotron-primary pl-2 mb-4">
				<div class="font-weight-bold text-uppercase">Posts</div>
				<hr class="mt-0 mb-2" />
				<a href="#" class="btn btn-dark btn-block text-left mb-2">Popular</a>
				<a href="#" class="btn btn-dark btn-block text-left mb-2">Newest</a>
			</div>
			<div class="quotron-primary pl-2 mb-4">
				<div class="font-weight-bold text-uppercase">Users</div>
				<hr class="mt-0 mb-2" />
				<a href="#" class="btn btn-dark btn-block text-left mb-2">Newest</a>
				<a href="#" class="btn btn-dark btn-block text-left mb-2">Active</a>
			</div>
		</div>
</div>