<?php

/**
 * @var Atlantis\Prototype\Blog $Blog
 * @var Atlantis\Prototype\BlogUser $BlogUser
 * @var Atlantis\Struct\SearchResult $Posts
 * @var Atlantis\Prototype\BlogPost $Post
 * @var Atlantis\Struct\SearchResult $Tags
 */

$PostListTitle = 'Latest Posts';
$PostListSubtitle = '';

if(is_array($QueryTags) && count($QueryTags)) {
	$PostListTitle = 'Posts Tagged With:';
	$PostListSubtitle = array_reduce(
		$QueryTags,
		function($Buffer,$Val) {
			return sprintf(
				'%s<span class="btn btn-sm btn-secondary pt-0 pb-0 mr-2">%s</span>',
				$Buffer,
				$Val->Title
			);
		},
		''
	);
}

echo (new Atlantis\Element\PagePromo)
->SetArea('element/page-promo-artsy')
->SetURL($Blog->URL)
->SetImageURL($Blog->ImageHeaderURL)
->SetIconURL($Blog->ImageIconURL)
->SetTitle($Blog->Title ?? '')
->SetSubtitle($Blog->Tagline ?? '');

?>


<div class="container">

<div class="row">

		<?php if($Blog->IsAdult()): ?>
		<div class="col-12 mb-4">
			<div class="alert alert-adult">
				<i class="fa fas fa-exclamation-square mr-2"></i>
				This blog contains Adult Content.
			</div>
		</div>
		<?php endif; ?>

		<div class="col-12 col-md mb-4">
			<div class="jumbotron jumbotron-secondary p-4 m-0">
			<?php
			echo (new Atlantis\Element\PostListing)
			->AddClasses('NoBlogIcon')
			->SetTitle($PostListTitle)
			->SetSubtitle($PostListSubtitle)
			->SetItemStore($Posts->Payload);
			?>
			</div>
		</div>
		<div class="col-12 col-lg-4 mb-4BlogSidebar">

			<div class="row">
				<div class="col-12 col-md-6 col-lg-12 mb-4">

					<?php if($BlogUser):?>
					<div class="mb-4">
						<?php if($BlogUser->HasWritePriv()): ?>
						<a class="btn btn-dark btn-block text-left mb-2" href="<?php $Printer($Endpoint('Atlantis.Dashboard.Blog.Post.New',['BlogID'=>$Blog->ID])) ?>"><i class="fas fa-fw fa-pen mr-1"></i> Write</a>
						<?php endif; ?>
						<?php if($BlogUser->HasManagePriv()): ?>
						<a class="btn btn-dark btn-block text-left mb-2" href="<?php $Printer($Endpoint('Atlantis.Dashboard.Blog.Settings',['BlogID'=>$Blog->ID])) ?>"><i class="fas fa-fw fa-wrench mr-1"></i> Settings</a>
						<?php endif; ?>
					</div>
					<?php endif; ?>

					<!-- ABOUT -->
					<?php if($Blog->Details): ?>
					<div class="jumbotron jumbotron-secondary p-4 mb-4">
						<h2 class="font-size-normal">
							About
						</h2>
						<hr class="mt-2 mb-2" />
						<div class="row tight align-items-center justify-content-center">
							<div class="col-12">
								<?php $Printer($Blog->Details) ?>
							</div>
						</div>
					</div>
					<?php endif; ?>

					<!-- TAGS -->
					<div class="jumbotron jumbotron-secondary p-4 mb-4">
						<h2 class="font-size-normal">
							Tags
						</h2>
						<hr class="mt-2 mb-2" />
						<div class="row tight align-items-center justify-content-center">
						<?php if($Tags->Count): ?>
						<?php foreach($Tags->Payload as $Tag): ?>
							<div class="col-auto mb-1">
								<a href="<?php $Printer($Blog->GetTagURL($Tag)) ?>" class="btn btn-sm btn-secondary pt-0 pb-0"><?php $Printer($Tag->Title) ?></a>
							</div>
						<?php endforeach; ?>
						<?php else: ?>
							<div class="col text-center">This blog has no tags yet.</div>
						<?php endif; ?>
						</div>
					</div>

					<!-- USERS -->
					<div class="jumbotron jumbotron-secondary p-4 m-0 HideTheLastHr">
						<h2 class="font-size-normal">
							Bloggers
						</h2>
						<hr class="mt-2 mb-2" />
						<?php foreach($Bloggers->Payload as $Blogger): ?>
						<div class="row tight align-items-center justify-content-center">
							<div class="col-3">
								<div class="WallpaperedBox Square rounded" style="background-image:url(<?php $Printer($Blogger->User->GetImageIconURL('th')) ?>);">
									<a href="<?php $Printer($Blogger->User->GetURL()) ?>"></a>
								</div>
							</div>
							<div class="col">
								<div class="text-uppercase font-size-smallerer font-weight-bold"><?php $Printer($Blogger->GetRoleWord()) ?></div>
								<a href="<?php $Printer($Blogger->User->GetURL()) ?>" class="font-size-large font-weight-bold"><?php $Printer($Blogger->User->Alias) ?></a>
								<?php if($Blogger->User->Location): ?><div><?php $Printer($Blogger->User->Location) ?></div><?php endif; ?>
							</div>
						</div>
						<hr />
						<?php endforeach; ?>
					</div>

				</div>
				<div class="col-12 col-md-6 col-lg-12 mb-4">

					<!-- POPULAR POSTS -->
					<div class="jumbotron jumbotron-secondary p-4 m-0">
					<?php
					echo (new Atlantis\Element\PostListingSidebar)
					->SetTitle('Popular Posts')
					->SetItemStore($PopularPosts->Payload);
					?>

					</div>
				</div>
			</div>

		</div>
	</div>

</div>


