<?php

/**
 * @var Atlantis\Prototype\Blog $Blog
 * @var Atlantis\Struct\SearchResult $Posts
 * @var Atlantis\Prototype\BlogPost $Post
 */

echo (new Atlantis\Element\PagePromo)
->SetURL($Blog->URL)
->SetImageURL($Blog->ImageHeaderURL)
->SetIconURL($Blog->ImageIconURL)
->SetTitle($Blog->Title ?? '')
->SetSubtitle($Blog->Tagline ?? '');

?>


<div class="container">

	<div class="row">
		<?php if($Blog->IsAdult()): ?>
		<div class="col-12 mb-4">
			<div class="alert alert-adult">
				<i class="fa fas fa-exclamation-square mr-2"></i>
				This blog contains Adult Content.
			</div>
		</div>
		<?php endif; ?>

		<div class="col-12 col-md mb-4">

			<?php
			echo (new Atlantis\Element\PostListing)
			->SetTitle('Recent Posts')
			->SetItemStore($Posts->Payload);
			?>

		</div>
		<div class="col-12 col-md-4 mb-4 BlogSidebar">
			sidebar
		</div>
	</div>

</div>


