<?php

/**
 * @var Atlantis\Prototype\Blog $Blog
 * @var Atlantis\Prototype\BlogPost $Post
*/

echo (new Atlantis\Element\PagePromo)
->SetURL($Blog->URL)
->SetTitle($Blog->Title)
->SetSubtitle($Blog->Tagline);

?>

<div class="container">

	<h2><?php echo $Post->Title ?></h2>
	<div class="mb-4">
		Posted on <?php echo $Post->DateCreated->Format('F jS g:ia'), PHP_EOL ?>
	</div>

	<div>

<?php echo $Post->Content, PHP_EOL ?>

	</div>

</div>
