<?php

/**
 * @var Routes\Blog\Post $Route
 * @var Atlantis\Prototype\Blog $Blog
 * @var Atlantis\Prototype\BlogPost $Post
 * @var Atlantis\Prototype\BlogUser $BlogUser
 * @var Atlantis\Struct\SearchResult $Tags
 * @var Bool $UserCanEdit
 * @var Bool $UserCanDelete
*/

echo (new Atlantis\Element\PagePromo)
->SetArea('element/page-promo-artsy')
->SetURL($Blog->URL)
->SetImageURL($Blog->ImageHeaderURL)
->SetIconURL($Blog->ImageIconURL)
->SetTitle($Blog->Title)
->SetSubtitle($Blog->Tagline ?: '');

?>

<div class="container">
	<div class="row">
		<?php if($Post->IsAdult()): ?>
		<div class="col-12 mb-4">
			<div class="alert alert-adult mb-0">
				<i class="fa fas fa-exclamation-square mr-2"></i>
				This post contains Adult Content.
			</div>
		</div>
		<?php endif; ?>

		<?php if($Post->IsDraft()): ?>
		<div class="col-12 mb-4">
			<div class="alert alert-dark mb-0">
				<i class="fa fas fa-sticky-note mr-2"></i>
				This post is saved as a Draft.
			</div>
		</div>
		<?php endif; ?>

		<div class="col-12 mb-4">

			<!-- POST HEADING -->
			<div class="row">
				<div class="col-12 mb-1">
					<?php $Printer($Post->DateCreated->Format('F jS g:ia')) ?>
				</div>
				<div class="col-12 mb-2">
					<h3 class="font-weight-bold mb-2"><a href="<?php $Post->URL ?>"><?php $Printer($Post->Title) ?></a></h3>
					<div class="row tight align-items-center">
						<?php foreach($Tags->Payload as $PostTag): ?>
						<div class="col-auto">
							<a href="<?php $Printer($Blog->GetTagURL($PostTag->Tag)) ?>" class="btn btn-sm btn-secondary pt-0 pb-0"><?php $Printer($PostTag->Tag->Title) ?></a>
						</div>
						<?php endforeach; ?>
						<?php if($UserCanEdit || $UserCanDelete): ?>
						<div class="col-auto">|</div>
						<?php endif ?>
						<?php if($UserCanEdit): ?>
						<div class="col-auto">
							<a class="btn btn-sm btn-dark pt-0 pb-0" href="<?php echo $Endpoint('Atlantis.Dashboard.Blog.Post.Edit',['PostID'=>$Post->ID]) ?>">Edit</a>
						</div>
						<?php endif; ?>
						<?php if($UserCanDelete): ?>
						<div class="col-auto">
							<a class="btn btn-sm btn-dark pt-0 pb-0 AtlantisActionPostDelete" href="#" data-post-id="<?php echo $Post->ID ?>">Delete</a>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<hr />

			<?php if($Post->IsAdult() && $Route->ShouldAdultSafespace()): ?>
			<!-- ADULT CONTENT WARNING -->
			<div class="alert alert-adult mb-0">
				<?php if($User): ?>
				<p>
					This post has been hidden because your account settings are currently configured to not display adult content.
					You may change the setting in your dashboard <a href="<?php echo $Endpoint('Atlantis.Dashboard.Account.Settings') ?>">Account Settings</a>.
				</p>
				<?php else: ?>
				<p>
					This post has been hidden because you are not <a href="<?php echo $Endpoint('Atlantis.Login') ?>">logged in</a>. It has been suggested I mention that by clicking "View Post Anyway" you are acknowledging you are at least 18 years of age.
				</p>
				<?php endif; ?>
				<div class="text-center">
					<form method="post">
						<input type="hidden" name="Action" value="ignore-adult-safespace" />
						<button type="submit" class="btn btn-adult">View Post Anyway</button>
					</form>
				</div>
			</div>
			<hr />
			<?php else: ?>
			<div class="mb-0">
				<div class="PostContent">
					<?php if($Route->Get->ShowJson): ?>
					<pre class="CodeViewer" data-mime="application/json" data-title="EditorJS Structure" data-theme="synthwave84"><?php echo json_encode(json_decode($Post->ContentJSON),JSON_PRETTY_PRINT) ?></pre>
					<?php endif; ?>
					<?php echo new Atlantis\Util\Texture($Post->Content ?: $Post->RenderFromJSON()), PHP_EOL ?>
				</div>
			</div>
			<?php endif; ?>
		</div>

		<div class="col-12 mb-4">
			<div class="jumbotron jumbotron-secondary p-4 m-0">
				<h3 class="font-weight-bold">Comments (<span class="PostCommentCount">#</span>)</h3>
				<hr />
				<div id="PostComments" data-post-id="<?php $Printer($Post->ID) ?>">
					<div class="PostCommentTemplate d-none">
						<div class="row">
							<div class="col-3 col-sm-2 col-md-2 col-lg-1">
								<div class="PostCommentIcon wallpapered background-primary ratio-square rounded w-100" style="background-image:url(<?php $Printer(Nether\Option::Get('Atlantis.Blog.DefaultImageIconURL')) ?>);"></div>
							</div>
							<div class="col">
								<div class="PostCommentHeading font-size-smaller text-muted">
									<span class="PostCommentDate">[Date]</span> by
									<span class="PostCommentName">[Name]</span>
								</div>
								<div class="PostCommentBody">[Comment Body]</div>
							</div>
						</div>
						<hr />
					</div>
				</div>
				<div class="pt-4 pb-4">
					<?php if($Post->IsCommentingAllowed($User)): ?>
						<div class="text-center font-weight-bold mb-2">Comments don't actually work yet.</div>
						<div class="text-center font-size-largerer mb-4">(っ˘̩╭╮˘̩)っ</div>
						<div id="CommentForm" class="row">
							<?php if($User): ?>
							<input type="hidden" name="UserID" value="<?php $Printer($User->ID) ?>" />
							<?php else: ?>
							<div class="col-12 col-sm-6 col-md-4 mb-2">
								<input type="text" name="Name" class="form-control" placeholder="Your Name..." />
							</div>
							<?php endif; ?>
							<div class="col-12 mb-2">
								<textarea name="Content" class="form-control" placeholder="Your Comment..."></textarea>
							</div>
							<div class="col-12 mb-0">
								<button type="button" class="btn btn-dark CmdCommentPost">Post Comment</button>
							</div>
						</div>
					<?php else: ?>
						<div class="text-center font-weight-bold mb-2">Comments are disabled.</div>
						<div class="text-center font-size-largerer">(っ˘̩╭╮˘̩)っ</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="col-12 col-md-6 mb-4">
			<div class="jumbotron jumbotron-secondary p-4 m-0">
			<?php
			if($PopularPosts->Total)
			echo (new Atlantis\Element\PostListingSidebar)
			->SetTitle('Popular Posts')
			->SetSubtitle(sprintf('From %s',$Blog->Title))
			->SetItemStore($PopularPosts->Payload);
			?>
			</div>
		</div>

		<div class="col-12 col-md-6 mb-4">
			<div class="jumbotron jumbotron-secondary p-4 m-0">
			<?php
			echo (new Atlantis\Element\PostListingSidebar)
			->SetTitle('Recent Posts')
			->SetSubtitle(sprintf('From %s',$Blog->Title))
			->SetItemStore($RecentPosts->Payload);
			?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
class AtlantisPostComments {

	constructor(Selector) {
	/*//
	@date 2020-12-11
	//*/

		this.Container = jQuery(Selector);
		this.PostID = this.Container.attr('data-post-id');
		this.Page = 1;
		this.PageCount = 1;
		this.CommentCount = 0;

		this.Template = (
			this.Container
			.find('.PostCommentTemplate')
			.clone()
			.removeClass('d-none')
		);

		this.Loading = (
			jQuery('<div />')
			.addClass('d-none')
			.addClass('Loading')
			.addClass('text-center')
			.append('<i class="fa fa-fw fa-spin fa-asterisk"></i> Loading...')
		);

		this.Listing = (
			jQuery('<div />')
			.addClass('d-none')
			.addClass('Listing')
		);


		(this.Container)
		.append(this.Loading)
		.append(this.Listing);

		this.LoadPage(1);
		return;
	}

	LoadNextPage() {
	/*//
	@date 2020-12-11
	//*/

		if(this.Page < this.PageCount)
		this.LoadPage(this.Page + 1);

		return;
	}

	LoadPrevPage() {
	/*//
	@date 2020-12-11
	//*/

		if(this.Page > 1)
		this.LoadPage(this.Page - 1);

		return;
	}

	async LoadPage(PageNum) {
	/*//
	@date 2020-12-11
	//*/

		let Result = null;
		let Element = null;

		this.ShowLoading();

		Result = await this.FetchPage(PageNum);
		console.log(Result);
		this.Page = Result.Payload.Page;
		this.PageCount = Result.Payload.PageCount;
		this.CommentCount = Result.Payload.Total;

		for(const Comment of Result.Payload.Comments) {
			Element = this.Template.clone();

			Element
			.find('.PostCommentBody')
			.text(Comment.Content);

			Element
			.find('.PostCommentDate')
			.text(Comment.DateTimeCreated);

			Element
			.find('.PostCommentName')
			.text(Comment.Name);

			if(Comment.User) {
				Element
				.find('.PostCommentIcon')
				.css('background-image',`url(${Comment.User.ImageIcon.Tiny})`);

				Element
				.find('.PostCommentName')
				.html(`<a href="${Comment.User.URL}">${Comment.Name}</a>`);
			}

			this.Listing.append(Element);
		}

		this.ShowListing();

		return;
	}

	async FetchPage(PageNum) {
	/*//
	@date 2020-12-11
	//*/

		let that = this;
		let Result = null;

		return (
			new Promise(function(Next,Fail){
				Atlantis.Request({
					'Method': 'LIST',
					'URL': '/api/v1/post/comment',
					'Data': { 'ID': that.PostID },
					'OnSuccess': function(Result){ Next(Result); return; },
					'OnError': function() { Fail(); return; }
				});
			})
			.then(function(Result){ return Result; })
		);
	}

	ShowLoading() {
	/*//
	@date 2020-12-11
	//*/

		this.Listing.addClass('d-none');
		this.Loading.removeClass('d-none');

		return;
	}

	ShowListing() {
	/*//
	@date 2020-12-11
	//*/

		this.Loading.addClass('d-none');
		this.Listing.removeClass('d-none');

		return;
	}



}

jQuery(document)
.ready(function(){
	new AtlantisPostComments('#PostComments');
	return;
});
</script>

