<?php

$Printer = new Nether\Input\Filter($_POST);
$Printer->SetDefaultFunction('Atlantis\\Util\\Filters::SafeForHTML');

?>

<style type="text/css">
.g-recaptcha > div { margin: 0px auto; width: 100%; }
</style>

<div class="container pt-4 pb-4">

	<div class="row justify-content-center">
		<div class="col-12 col-sm-6 col-md-5">
			<h3 class="mb-0">Join</h2>
			<hr class="mt-2 mb-2" />
			<form method="post">
				<div class="form-group mb-2">
					<input type="text" name="Alias" class="form-control" placeholder="Username..." value="<?php echo $Printer->Alias ?>" />
				</div>
				<div class="form-group mb-2">
					<input type="text" name="Email" class="form-control" placeholder="Email..." value="<?php echo $Printer->Email ?>" />
				</div>
				<div class="form-group mb-2">
					<input type="password" name="Password1" class="form-control" placeholder="Password..."  value="<?php echo $Printer->Password1 ?>" />
				</div>
				<div class="form-group mb-2">
					<input type="password" name="Password2" class="form-control" placeholder="Password Again..." value="<?php echo $Printer->Password2 ?>" />
				</div>
				<div class="form-group mb-2">
					<div class="g-recaptcha" data-sitekey="<?php echo Nether\Option::Get('Google.ReCaptcha.Key') ?>"></div>
				</div>
				<div class="form-group mb-2">
					<input type="hidden" name="Action" value="lulz" />
					<input type="submit" class="btn btn-block btn-dark" value="Create Account" />
				</div>
			</form>
		</div>
	</div>
</div>
