
<footer>
	<div class="container">
		<div class="row mb-4">
			<div class="col-12 col-md-auto mb-4">
				<code><?php Theme::RenderAppStats(); ?></code>
			</div>
			<div class="col-12 col-md mb-4"></div>
			<div class="col-12 col-md-auto mb-4">
				<a href="https://github.com/bobmagicii/atlantis" target="_blank"><i class="fab fa-github"></i> Github</a>
			</div>
			<?php if($User && $User->IsAdmin()): ?>
			<div class="col-12 mb-4">
				<?php $Surface->Area('design/footer-dev') ?>
			</div>
			<?php endif; ?>
		</div>
	</div>

	<?php $Surface->Area('design/footer-local') ?>
</footer>
