
<footer>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-auto mb-4 mb-md-0">
				<code><?php Theme::RenderAppStats(); ?></code>
			</div>
			<div class="col-12 col-md mb-4 mb-md-0"></div>
			<div class="col-12 col-md-auto mb-4 mb-md-0">
				<a href="https://github.com/bobmagicii/atlantis" target="_blank"><i class="fab fa-github"></i> Github</a>
			</div>
		</div>
	</div>
</footer>
