<?php foreach(Nether\Database::$QueryLog as $Query): ?>
<div class="quotron quotron-primary mb-4">
	<?php foreach($Query->Trace as $Trace): ?>
	<div class="font-weight-bold"><i class="fas fa-fw fa-angle-double-right"></i><?php $Printer($Trace) ?></div>
	<?php endforeach; ?>
	<code class="d-block m-0 p-0" style="overflow:hidden;max-height:100px;" onclick="(jQuery(this).css('max-height') !== '100px')?(jQuery(this).css('max-height','100px')):(jQuery(this).css('max-height','initial'));"><?php echo(SqlFormatter::format($Query->Query)) ?></code>
	<?php if(count($Query->Input)) Atlantis\Util::VarDump($Query->Input) ?>
</div>
<?php endforeach; ?>
