<?php

/**
 * @var Atlantis\Prototype\User $Profile
 */

use Atlantis\Element\PostListing;
use Atlantis\Element\PagePromo;

////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////

echo (new PagePromo)
->SetArea('element/page-promo-artsy')
->SetURL($Profile->GetURL())
->SetImageURL($Profile->GetImageHeaderURL('lg'))
->SetIconURL($Profile->GetImageIconURL('th'))
->SetTitle($Profile->Alias)
->SetSubtitle('User Profile')

?>

<div class="container pb-4">

	<div class="row">
		<div class="col-12">

		</div>
		<div class="col-12 col-md-6">

			<?php
			echo (new PostListing)
			->SetTitle("Recent Posts by {$Profile->Alias}")
			->SetItemStore($RecentPosts->Payload)
			->SetShowPostPreview(FALSE)
			->SetShowPostImage(PostListing::PostImagePreview);
			?>

		</div>

		<div class="col-12 col-md">
			<div class="quotron-primary pl-2 mb-6">
				<div class="PostListing HideTheLastHr">
					<h2 class="font-size-normal">
						About
					</h2>
					<hr class="mt-2 mb-3" />
					<div class="">
						<?php echo nl2br($Encoder($Profile->Details ?: "{$Profile->Alias} has not added a profile bio.")) ?>
					</div>
					<hr />
					<?php if($Profile->Location): ?>
					<div class="">
						<strong class="font-weight-bold">Location:</strong> <?php $Printer($Profile->Location) ?>
					</div>
					<?php endif; ?>
					<hr />
				</div>
			</div>
			<div class="quotron-primary pl-2 mb-6">
				<?php
				echo (new Atlantis\Element\BlogListing)
				->SetItemStore($Blogs->Payload->Map(fn($Val)=> $Val->Blog))
				?>
			</div>
		</div>
	</div>

</div>