<?php

/**
 * @var Atlantis\Datastore $Posts
 * @var Atlantis\Blog\Post $Post
 */

echo (new Atlantis\Element\PagePromo)
->SetTitle('Oh Snap')
->SetSubtitle(
	"This theme is not even blue.\n".
	"With a name like that you think it would be."
);

?>

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mb-4">

			<h3>Latest Posts</h3>
			<hr />
			<?php foreach($Posts->Payload as $Post): ?>
			<div>
				<div><a href="<?php echo $Post->GetURL() ?>"><?php echo Atlantis\Util\Filters::SafeForHTML($Post->Title) ?></a></div>
				<div>
					Posted on <?php echo $Post->DateCreated->Format('F jS g:ia') ?>
					From <a href="<?php echo $Post->Blog->GetURL() ?>"><?php echo $Post->Blog->Title ?></a>
					By <a href="<?php echo $Post->User->GetURL() ?>"><?php echo $Post->User->Alias ?></a>
				</div>
			</div>
			<?php endforeach; ?>

		</div>
		<div class="col-12 col-md-4 mb-4">
			[Sidebar]
		</div>
	</div>
</div>
