<?php

/**
 * @var Atlantis\Datastore $PopularPosts
 * @var Atlantis\Datastore $Posts
 * @var Atlantis\Blog\Post $Post
 */

echo (new Atlantis\Element\PagePromo)
->AddClasses('mb-')
->SetTitle('Fancy Area')
->SetSubtitle('This would be a great place for something attention grabbing.');

?>

<div class="container">
	<div class="row">
		<div class="col-12 col-lg-8">

			<div class="jumbotron jumbotron-secondary p-4 mb-4">
			<?php
			if($Posts->Total)
			echo (new Atlantis\Element\PostListing)
			->SetTitle('Recent Posts')
			->SetItemStore($Posts->Payload);
			?>
			</div>

		</div>
		<div class="col-12 col-lg-4">

			<div class="row">
				<div class="col-12 col-md-6 col-lg-12 mb-4">
					<div class="jumbotron jumbotron-secondary p-4 m-0">
						[Recent User List]
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-12 mb-4">
					<div class="jumbotron jumbotron-secondary p-4 m-0">
					<?php
					echo (new Atlantis\Element\PostListingSidebar)
					->SetTitle('Popular Posts')
					->SetItemStore($PopularPosts->Payload);
					?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
