<?php

/**
 * @var Atlantis\Prototype\User $User
 * @var Atlantis\Prototype\Blog $Blog
 */

// Atlantis\Util::VarDump(ini_get('upload_max_filesize'));

?>

<?php $Surface->Area('dashboard/promo') ?>

<div id="BlogConfig" class="d-none" data-blog-id="<?php $Printer($Blog->ID) ?>"></div>

<div class="container pb-4">
	<div class="breadcrumb mb-6">
		<div class="breadcrumb-item"><a href="<?php echo Atlantis\Site\Endpoint::Get('Atlantis.Dashboard.Home') ?>">Dashboard</a></div>
		<div class="breadcrumb-item">Blogs</div>
		<div class="breadcrumb-item">
			<div class="dropdown" style="display:inline-block">
				<a href="#" class="" data-toggle="dropdown"><?php $Printer($Blog->Title) ?></a>
				<div class="dropdown-menu">
					<div class="dropdown-item">[list-o-blogs]</div>
				</div>
			</div>
		</div>
		<div class="breadcrumb-item active">Settings</div>
	</div>

	<!-- IMAGES -->
	<div class="row align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Blog Graphics</h2>
			<hr class="mb-2 mt-2" />
			You can set a Profile Icon and a Header Image for your blog.
		</div>
		<div class="col-12 mb-2">
			<?php
			echo (new Atlantis\Element\PagePromo)
			->SetURL($Blog->URL)
			->SetImageURL($Blog->ImageHeaderURL)
			->SetIconURL($Blog->ImageIconURL)
			->SetTitle($Blog->Title ?? '')
			->SetSubtitle($Blog->Tagline ?? '')
			->AddClasses('mb-0','rounded','BlogHeaderDemo');
			?>
		</div>
		<div class="col-12 col-md-6 mb-2 mb-md-0">
			<div class="row tight">
				<div class="col">
					<button id="CmdImageIcon" class="btn btn-dark btn-lg btn-block"><i class="fas fa-fw fa-image"></i> Upload Icon</button>
					<input type="file" class="d-none" id="InputImageIcon" />
				</div>
				<div class="col-auto">
					<button id="CmdRemoveImageIcon" class="btn btn-danger btn-lg"><i class="fas fa-fw fa-times"></i></button>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-6 mb-2 mb-md-0">
			<div class="row tight">
				<div class="col">
					<button id="CmdImageHeader" class="btn btn-dark btn-lg btn-block"><i class="fas fa-fw fa-image"></i> Upload Header</button>
					<input type="file" class="d-none" id="InputImageHeader" />
				</div>
				<div class="col-auto">
					<button id="CmdRemoveImageHeader" class="btn btn-danger btn-lg"><i class="fas fa-fw fa-times"></i></button>
				</div>
			</div>
		</div>
	</div>

	<!-- TITLE -->
	<div id="DashBlogTitle" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Title</h2>
			<hr class="mb-2 mt-2" />
			The primary name of your blog.
		</div>
		<div class="col mb-2">
			<input id="InputTitle" type="text" autocomplete="off" class="form-control" placeholder="Enter Blog Title Here..." value="<?php echo $Printer($Blog->Title) ?>" />
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<div class="col-auto mb-2">
			<butt type="button" class="btn btn-block btn-dark ActionCommit">Save</button>
		</div>
	</div>

	<!-- TAGLINE -->
	<div id="DashBlogTagline" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Tag Line</h2>
			<hr class="mb-2 mt-2" />
			Some little flavour text usually shown underneath your blog title.
		</div>
		<div class="col mb-2">
			<input id="InputTagline" type="text" autocomplete="off" class="form-control" placeholder="Enter Tag Line Here..." value="<?php echo $Printer($Blog->Tagline) ?>" />
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<div class="col-auto mb-2">
			<button type="button" class="btn btn-block btn-dark ActionCommit">Save</button>
		</div>
	</div>

	<!-- Details -->
	<div id="DashBlogDetails" class="row tight align-items-end mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Details</h2>
			<hr class="mb-2 mt-2" />
			A short description about the type of things you are going to blog about.
		</div>
		<div class="col mb-2">
			<textarea id="InputDetails" type="text" autocomplete="off" class="form-control" placeholder="Enter Details Here..."><?php echo $Printer($Blog->Details) ?></textarea>
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<div class="col-auto mb-2">
			<button type="button" class="btn btn-block btn-dark ActionCommit">Save</button>
		</div>
	</div>

	<!-- ALIAS -->
	<div id="DashBlogAlias" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Blog URL</h2>
			<hr class="mb-2 mt-2" />
			This is the address of your blog. Changing it will break any links you have shared in the past.
		</div>
		<div class="col-auto mb-2">
			<span class="font-family-code"><?php echo $Router->GetDomain() ?></span>
		</div>
		<div class="col-auto mb-2">
			<span class="font-family-code">/</span>
		</div>
		<div class="col-auto mb-2">
			<span class="font-family-code">+</span>
		</div>
		<div class="col mb-2">
			<input id="InputAlias" type="text" autocomplete="off" class="form-control font-family-code" placeholder="Enter URL Here..." value="<?php echo $Printer($Blog->Alias) ?>" />
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<div class="col-auto mb-2">
			<button type="button" class="btn btn-block btn-dark ActionCommit">Save</button>
		</div>
	</div>

	<!-- ADULT CONTENT -->
	<div id="DashBlogOptAdult" class="mb-0">
		<h2 class="font-size-large font-weight-bold">Adult Content</h2>
		<hr class="mb-2 mt-2" />
		<p>
			Adult content is allowed but in return it is asked you flag the blog as adult so we can filter for those who desire it.
			When your blog is flagged as adult we may do a few things like place a warning, blur images, or filter, based on the viewer's preferences.
		</p>
		<p>
			Each post you make may also be flagged as adult or not. There is nothing stopping you from having 1 adult post on a non-adult blog, or 1 non-adult post on an adult blog. Keep in mind most readers will probably prefer if your blog remains on its original topic.
			I reserve the right to force the adult flag on blogs or posts if you are being dishonorable about it, but please don't make me do that.
		</p>
		<?php if($Blog->OptAdult===$Blog::AdultForced): ?>
		<div class="alert alert-dark mb-2 p-2">
			<div class="row align-items-center">
				<div class="col-3"><img src="/share/dist/gfx/honor.jpg" class="rounded" /></div>
				<div class="col">Your honor has been tested and found lacking. This blog has been forced into Adult Mode and may no longer be changed. All future posts will also be forced into Adult Mode.</div>
			</div>
		</div>
		<?php else: ?>
		<div class="row tight align-items-center">
			<div class="col-auto">
				<button id="InputOptAdult" class="ActionCommit btn btn-adult btn-block btn-toggle <?php $Printer($Blog->OptAdult?'active':'') ?>">
					<i class="btn-toggle-off far fa-square mr-2"></i>
					<i class="btn-toggle-on far fa-check-square mr-2"></i>
					My blog contains Adult Content.
				</button>
			</div>
			<div class="col-auto">
				<div class="d-flex">
					<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
					<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
					<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
				</div>
			</div>
			<div class="col">

			</div>
		</div>
		<?php endif; ?>
	</div>

</div>

<script type="module">
import UploadButton from '/share/atlantis/element/upload-button.js';

jQuery(document)
.ready(function(){

	let BlogConfig = jQuery('#BlogConfig');
	let BlogID = BlogConfig.attr('data-blog-id');

	let Title = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogTitle',
		'OnCommit': function(Handler){
			let Input = jQuery.trim(jQuery('#InputTitle').val());

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'Title': Input } },
				'OnSuccess': function(Result){
					jQuery('.BlogHeaderDemo h2').text(Result.Payload.Title);
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Your blog title has been successfully updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let Tagline = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogTagline',
		'OnCommit': function(Handler){
			let Input = jQuery.trim(jQuery('#InputTagline').val());

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'Tagline': Input } },
				'OnSuccess': function(Result){
					jQuery('.BlogHeaderDemo p').text(Result.Payload.Tagline);
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Your blog tagline has been successfully updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let Details = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogDetails',
		'OnCommit': function(Handler){
			let Input = jQuery.trim(jQuery('#InputDetails').val());

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'Details': Input } },
				'OnSuccess': function(Result){
					jQuery('.BlogHeaderDemo p').text(Result.Payload.Tagline);
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Your blog details has been successfully updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let Alias = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogAlias',
		'OnCommit': function(Handler){
			let Input = jQuery.trim(jQuery('#InputAlias').val());

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'Alias': Input } },
				'OnSuccess': function(Result){
					jQuery('.BlogHeaderDemo a').attr('href',('/+' + Result.Payload.Alias));
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Your blog URL has been successfully updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		},
		'OnKeyPress': function(Handler){

			let Final = jQuery.trim(
				jQuery('#InputAlias')
				.val()
				.toLowerCase()
				.replace(/[^a-z0-9\x20\-]/g,'')
				.replace(/ /g,'-')
				.replace(/-{2,}/g,'-')
				.substr(0,64)
			);

			Handler.SetStatus(null);
			jQuery('#InputAlias').val(Final);
			return;
		}
	});

	let OptAdult = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogOptAdult',
		'OnCommit': function(Handler){
			let Input = jQuery('#InputOptAdult').hasClass('active') ? 1 : 0;

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'OptAdult': Input } },
				'OnSuccess': function(Result){
					Handler
					.SetStatus('good')
					.Notify({
						'Title': 'Blog Settings',
						'Content': 'Your blog Adult Content setting has been updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler
					.SetStatus('bad')
					.Notify({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let UploadIcon = new UploadButton({
		'SelectorButton': '#CmdImageIcon',
		'SelectorInput': '#InputImageIcon',
		'FileType': UploadButton.FileTypeImage,
		'URL': '/api/v1/blog/icon',
		'Data': {
			'ID': BlogConfig.attr('data-blog-id')
		},
		'OnItemComplete': function(Status,Result,File){
			if(Result.Error !== 0) {
				alert(Result.Message);
			}

			jQuery('.BlogHeaderDemo .ImageIcon')
			.css('background-image','url(' + Result.Payload.ImageURL + ')')

			return;
		},
		'OnQueueComplete': function(){
			this.Reset();
			return;
		}
	});

	let UploadHeader = new UploadButton({
		'SelectorButton': '#CmdImageHeader',
		'SelectorInput': '#InputImageHeader',
		'FileType': UploadButton.FileTypeImage,
		'URL': '/api/v1/blog/header',
		'Data': {
			'ID': BlogConfig.attr('data-blog-id')
		},
		'OnItemComplete': function(Status,Result,File){
			if(Result.Error !== 0) {
				alert(Result.Message);
			}

			jQuery('.BlogHeaderDemo')
			.css('background-image','url(' + Result.Payload.ImageURL + ')')

			return;
		},
		'OnQueueComplete': function(){
			this.Reset();
			return;
		}
	});

	jQuery('#CmdRemoveImageIcon')
	.on('click',function(){

		if(confirm('Reset the icon image to default?'))
		Atlantis.Request({
			'Method': 'PATCH',
			'URL': '/api/v1/blog/entity',
			'Data': { 'ID': BlogID, 'Fields': { 'RemoveImageIcon': 1 } },
			'OnSuccess': function(Result){
				jQuery('.BlogHeaderDemo .ImageIcon')
				.css('background-image','url(' + Result.Payload.ImageIconURL + ')')

				return;
			}
		});

		return;
	});

	jQuery('#CmdRemoveImageHeader')
	.on('click',function(){

		if(confirm('Reset the header image to default?'))
		Atlantis.Request({
			'Method': 'PATCH',
			'URL': '/api/v1/blog/entity',
			'Data': { 'ID': BlogID, 'Fields': { 'RemoveImageHeader': 1 } },
			'OnSuccess': function(Result){
				jQuery('.BlogHeaderDemo')
				.css('background-image','url(' + Result.Payload.ImageHeaderURL + ')')

				return;
			}
		});

		return;
	});

	return;
});
</script>
