<?php

/**
 * @var Atlantis\User $User
 * @var Atlantis\Prototype\Blog $Blog
 */

// Atlantis\Util::VarDump(ini_get('upload_max_filesize'));

?>

<?php $Surface->Area('dashboard/promo') ?>

<div id="BlogConfig" class="d-none" data-blog-id="<?php $Printer($Blog->ID) ?>"></div>

<div class="container">

	<ol class="breadcrumb mb-6">
		<li class="breadcrumb-item"><a href="<?php echo Atlantis\Site\Endpoint::Get('Atlantis.Dashboard.Home') ?>">Dashboard</a></li>
		<li class="breadcrumb-item">Blogs</li>
		<li class="breadcrumb-item"><?php $Printer($Blog->Title) ?></li>
		<li class="breadcrumb-item active">Settings</li>
	</ol>

	<!-- TAGLINE -->
	<div id="DashBlogTagline" class="row tight align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Tag Line</h2>
			Some little flavour text usually shown underneath your blog title.
		</div>
		<div class="col mb-2">
			<input id="InputTagline" type="text" class="form-control" placeholder="Enter Tag Line Here..." value="<?php echo $Printer($Blog->Tagline) ?>" />
		</div>
		<div class="col-auto mb-2">
			<div class="d-flex">
				<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
				<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
				<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
			</div>
		</div>
		<div class="col-auto mb-2">
			<button id="CmdTagline" type="button" class="btn btn-block btn-dark ActionCommit">Save</button>
		</div>
	</div>

	<!-- IMAGES -->
	<div class="row align-items-center mb-6">
		<div class="col-12 mb-2">
			<h2 class="font-size-large font-weight-bold">Blog Graphics</h2>
			You can set a Profile Icon and a Header Image for your blog.
		</div>
		<div class="col-12 mb-2">
			<?php
			echo (new Atlantis\Element\PagePromo)
			->SetURL($Blog->URL)
			->SetImageURL($Blog->ImageHeaderURL)
			->SetIconURL($Blog->ImageIconURL)
			->SetTitle($Blog->Title ?? '')
			->SetSubtitle($Blog->Tagline ?? '')
			->AddClasses('mb-0','rounded');
			?>
		</div>
		<div class="col-12 col-md-6 mb-2 mb-md-0">
			<div class="row tight">
				<div class="col">
					<button id="CmdImageIcon" class="btn btn-dark btn-lg btn-block"><i class="fas fa-fw fa-image"></i> Upload Icon</button>
					<input type="file" class="d-none" id="InputImageIcon" />
				</div>
				<div class="col-auto">
					<button id="CmdRemoveImageIcon" class="btn btn-danger btn-lg"><i class="fas fa-fw fa-times"></i></button>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-6 mb-2 mb-md-0">
			<div class="row tight">
				<div class="col">
					<button id="CmdImageHeader" class="btn btn-dark btn-lg btn-block"><i class="fas fa-fw fa-image"></i> Upload Header</button>
					<input type="file" class="d-none" id="InputImageHeader" />
				</div>
				<div class="col-auto">
					<button id="CmdRemoveImageHeader" class="btn btn-danger btn-lg"><i class="fas fa-fw fa-times"></i></button>
				</div>
			</div>
		</div>
	</div>

	<!-- ADULT CONTENT -->
	<div id="DashBlogOptAdult" class="mb-6">
		<h2 class="font-size-large font-weight-bold">Adult Content</h2>
		<p>
			Adult content is allowed but in return it is asked you flag the blog as adult so we can filter for those who desire it.
			When your blog is flagged as adult we may do a few things like place a warning, blur images, or filter, based on the viewer's preferences.
		</p>
		<p>
			Each post you make may also be flagged as adult or not. There is nothing stopping you from having 1 adult post on a non-adult blog, or 1 non-adult post on an adult blog. Keep in mind most readers will probably prefer if your blog remains on its original topic.
			I reserve the right to force the adult flag on blogs or posts if you are being dishonorable about it, but please don't make me do that.
		</p>
		<?php if($Blog->OptAdult===$Blog::AdultForced): ?>
		<div class="alert alert-dark mb-2 p-2">
			<div class="row align-items-center">
				<div class="col-3"><img src="/share/dist/gfx/honor.jpg" class="rounded" /></div>
				<div class="col">Your honor has been tested and found lacking. This blog has been forced into Adult Mode and may no longer be changed. All future posts will also be forced into Adult Mode.</div>
			</div>
		</div>
		<?php else: ?>
		<div class="row tight align-items-center">
			<div class="col-auto">
				<button id="InputOptAdult" class="ActionCommit btn btn-adult btn-block btn-toggle <?php $Printer($Blog->OptAdult?'active':'') ?>">
					<i class="btn-toggle-off far fa-square mr-2"></i>
					<i class="btn-toggle-on far fa-check-square mr-2"></i>
					My blog contains Adult Content.
				</button>
			</div>
			<div class="col-auto">
				<div class="d-flex">
					<i class="ActionStatus ActionStatusThink fa fas fa-cog fa-spin font-size-anim font-size-normal font-size-zero"></i>
					<i class="ActionStatus ActionStatusGood fa fas fa-check font-size-anim font-size-normal font-size-zero text-success"></i>
					<i class="ActionStatus ActionStatusBad fa fas fa-times font-size-anim font-size-normal font-size-zero text-danger"></i>
				</div>
			</div>
			<div class="col">

			</div>
		</div>
		<?php endif; ?>
	</div>

</div>

<script type="text/javascript">

jQuery(document)
.ready(function(){
	"use strict";

	let BlogConfig = jQuery('#BlogConfig');
	let BlogID = BlogConfig.attr('data-blog-id');

	let Tagline = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogTagline',
		'OnCommit': function(Handler){
			let Input = jQuery.trim(jQuery('#InputTagline').val());

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'Tagline': Input } },
				'OnSuccess': function(Result){
					Handler.SetStatus('good');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Your blog tagline has been successfully updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler.SetStatus('bad');
					Atlantis.Toaster({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let OptAdult = new Atlantis.Action.StatusHandler({
		'Element': '#DashBlogOptAdult',
		'OnCommit': function(Handler){
			let Input = jQuery('#InputOptAdult').hasClass('active') ? 1 : 0;

			Atlantis.Request({
				'Method': 'PATCH',
				'URL': '/api/v1/blog/entity',
				'Data': { 'ID': BlogID, 'Fields': { 'OptAdult': Input } },
				'OnSuccess': function(Result){
					Handler
					.SetStatus('good')
					.Notify({
						'Title': 'Blog Settings',
						'Content': 'Your blog Adult Content setting has been updated.',
						'ContentClass': 'alert-success'
					});
					return;
				},
				'OnError': function(Result) {
					Handler
					.SetStatus('bad')
					.Notify({
						'Title': 'Blog Settings',
						'Content': 'Error: ' + Result.Message,
						'ContentClass': 'alert-danger'
					});
					return;
				}
			});

			return;
		}
	});

	let UploadIcon = new Atlantis.Upload.Button({
		'SelectorButton': '#CmdImageIcon',
		'SelectorInput': '#InputImageIcon',
		'FileType': Atlantis.Upload.FileTypeImage,
		'URL': '/api/v1/blog/icon',
		'Data': {
			'ID': BlogConfig.attr('data-blog-id')
		}
	});

	let UploadHeader = new Atlantis.Upload.Button({
		'SelectorButton': '#CmdImageHeader',
		'SelectorInput': '#InputImageHeader',
		'FileType': Atlantis.Upload.FileTypeImage,
		'URL': '/api/v1/blog/header',
		'Data': {
			'ID': BlogConfig.attr('data-blog-id')
		}
	});

	jQuery('#CmdRemoveImageIcon')
	.on('click',function(){

		if(confirm('Reset the icon image to default?'))
		Atlantis.Request({
			'Method': 'PATCH',
			'URL': '/api/v1/blog/entity',
			'Data': { 'ID': BlogID, 'Fields': { 'RemoveImageIcon': 1 } },
			'OnSuccess': function(){ location.reload(true); return; }
		});

		return;
	});

	jQuery('#CmdRemoveImageHeader')
	.on('click',function(){

		if(confirm('Reset the header image to default?'))
		Atlantis.Request({
			'Method': 'PATCH',
			'URL': '/api/v1/blog/entity',
			'Data': { 'ID': BlogID, 'Fields': { 'RemoveImageHeader': 1 } },
			'OnSuccess': function(){ location.reload(true); return; }
		});

		return;
	});

	return;
});

</script>
