<style type="text/css">

.TwoCol1x3
> div:nth-child(1) {
	float: left;
	width: 25%;
}

.TwoCol1x3
> div:nth-child(2) {
	float: left;
	padding-left: 32px;
	width: 75%;
}

.TitleBox {
	border: 1px solid #ccc;
}

.TitleBox
.Title {
	font-size: 14px;
	font-weight: bold;
	margin: -8px 0px 0px 0px;
	text-align: center;
	text-transform: uppercase;
}

.TitleBox
.Title span {
	background: #eee;
	color: #bbb;
	padding: 0px 16px;
}

.TitleBox
.Box {
	font-size: 1em;
	padding: 6px;
}

.TagList {
	display: flex;
	justify-content: center;
	flex-wrap: wrap;

	font-size: 0px;
	list-style-type: none;
	margin: 0px 0px 0px 0px;
	overflow: hidden;
	padding: 0px;
}

.TagList
li {
	display: block;
	flex-grow: 1;
	margin: 4px;
	white-space: nowrap;
}

.TagList
li a {
	display: block;
	border: 1px solid #ccc;
	color: #888;
	font-size: 12px;
	padding: 4px 8px;
	text-align: center;
}

.TagList
li a:hover {
	background: #ccc;
	color: #fff;
}

</style>
<div class="TwoCol1x3">
	<div>

<div class="TitleBox">
	<div class="Title">
		<span>Title Box</span>
	</div>
	<div class="Box">
		<ul class="TagList">
			<li><a href="">Bananas</a></li>
			<li><a href="">Ball Gowns</a></li>
			<li><a href="">C</a></li>
			<li><a href="">Design</a></li>
			<li><a href="">HTML</a></li>
			<li><a href="">Holiday</a></li>
			<li><a href="">Gaming</a></li>
			<li><a href="">Javascript</a></li>
			<li><a href="">Standards</a></li>
			<li><a href="">PHP</a></li>
			<li><a href="">Pizza</a></li>
			<li><a href="">Rant</a></li>
		</ul>
	</div>
</div>

	</div>
	<div>
<p>Letter of Marque to go on account square-rigged topmast capstan Cat o'nine tails American Main flogging Privateer Pieces of Eight. Yo-ho-ho Sink me sloop parley main sheet lass tender loot bilge rat nipper. Gold Road Brethren of the Coast main sheet interloper cackle fruit matey trysail bilged on her anchor strike colors line.</p>
<p>Haul wind square-rigged hail-shot Sink me gangway piracy chase keelhaul crack Jennys tea cup fathom. Provost draft cutlass hulk topgallant gally flogging gangway rum marooned. Quarterdeck aft mizzenmast belay Pirate Round loot long clothes jury mast spanker hulk.</p>
<p>American Main Shiver me timbers Sail ho stern hornswaggle tender strike colors belay topsail gibbet. Booty no prey, no pay long clothes come about mizzenmast hang the jib me parley walk the plank loaded to the gunwalls. Lugger maroon tackle pillage marooned port ahoy grog blossom Sail ho topsail.</p>
<p>Handsomely walk the plank ye prow hearties fire ship heave down starboard careen dance the hempen jig. Bilged on her anchor maroon fire in the hole spirits transom Nelsons folly Barbary Coast gaff mizzen hulk. Gold Road take a caulk Pieces of Eight Shiver me timbers hornswaggle overhaul blow the man down topmast broadside Jolly Roger.</p>
<p>Hulk black spot gun nipperkin ballast aye piracy provost swab boatswain. Gunwalls port Brethren of the Coast pressgang starboard dead men tell no tales yawl yardarm avast blow the man down. Shrouds American Main galleon Admiral of the Black long boat jack square-rigged Cat o'nine tails gangway fathom.</p>
<p>Code of conduct topsail Buccaneer keelhaul furl yo-ho-ho Davy Jones' Locker fluke Shiver me timbers red ensign. Splice the main brace code of conduct six pounders jury mast blow the man down doubloon yawl Pirate Round haul wind lugger. Admiral of the Black careen Nelsons folly crack Jennys tea cup Jack Ketch spyglass long clothes handsomely booty Pirate Round.</p>
	</div>
	<hr class="FloatClear" />
</div>