<?php

$User = Nether\Stash::Get('User');

$PageErrors = function(Nether\Object\Datastore $Errors):Void {
	$Errors->Each(function(Atlantis\Site\Error\Inline $Inline):Void {
		printf(
			'<div class="Contain Error"><div>%s%s</div></div>',
			($Inline->GetIcon())?
				("<i class=\"fa {$Inline->GetIcon()}\"></i> "):
				(''),
			$Inline->GetMessage()
		);
	});
};

$PrimaryBar = function() use($User):Void {

	if($User) $Data = [
		'Home' => '/',
		"Logout ({$User->GetAlias()})" => '/logout/'
	];

	else $Data = [
		'Home' => '/',
		'Join' => '/join/',
		'Login' => '/login/'
	];

	foreach($Data as $Name => $URL)
	echo "<li><a href=\"{$URL}\">{$Name}</a></li>";

	return;
};

$AppStats = new class() {
	public function
	__toString():
	String {
		return "db{{$this->GetDatabase()}}<br />c{{$this->GetCache()}}";
	}
	public function
	GetCache():
	String {

		$Stat = Nether\Stash::Get('Cache')->GetStats();

		return sprintf(
			'qc(%d), hc(%d %d%%)',
			$Stat->QueryCount,
			$Stat->HitCount,
			($Stat->QueryCount===0)?:
			((($Stat->HitCount / $Stat->QueryCount) * 100))
		);
	}
	public function
	GetDatabase():
	String {

		return sprintf(
			'cn(%d), ct(%.3f), qn(%d), qt(%.3f)',
			Nether\Database::$ConnectCount,
			Nether\Database::$ConnectTime,
			Nether\Database::$QueryCount,
			Nether\Database::$QueryTime
		);
	}
};

?>
<!doctype html>
<html>
<head>
	<title><?php $surface->Show('page-title') ?></title>
	<link rel="icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<link rel="shortcut icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Share+Tech+Mono&amp;subset=latin-ext" />
	<link rel="stylesheet" type="text/css" href="/themes/default/design.css" />
	<link rel="stylesheet" type="text/css" href="/share/other/dist/styles.css" />
	<script type="text/javascript" src="/share/other/dist/scripts.js"></script>
	<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
</head>
<body>

<header class="Contain"><div>
	<h1>
		<a href="">
		<img src="/themes/default/gfx/icon-tiny.png" alt="A" />
		<?php echo htmlentities(Nether\Option::Get('app-name')) ?>
		</a>
	</h1>
	<nav>
		<ul>
<?php $PrimaryBar() ?>
		</ul>
	</nav>
</div></header>

<?php echo new Atlantis\Element\PagePromo ?>

<?php if($route->Errors->Count()) $PageErrors($route->Errors); ?>

<section class="Contain"><div>

<?php echo $surface->Get('stdout') ?>

</div></section>

<footer class="Contain"><div>
	<ul>
		<li><a href="https://github.com/bobmagicii/atlantis" target="_blank"><i class="fa fa-github"></i> Github</a></li>
	</ul>
	<code><?php echo $AppStats ?></code>
	<hr class="FloatClear" />
</div></footer>

</body>
</html>