<?php

require_once('theme.php');

$GetStylesheetURL = function(String $URI):String {
	if(ENV\DEV)
	return "{$URI}.php";

	return "{$URI}";
};

?>
<!doctype html>
<html>
<head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge" />
	<meta name="theme-color" content="#333" />

	<!-- local packages -->
	<link rel="icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<link rel="shortcut icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<!-- <script type="text/javascript" src="/share/dist/require.js"></script> -->
	<script type="text/javascript" src="<?php echo $GetStylesheetURL('/share/dist/scripts.js'); ?>"></script>
	<link type="text/css" rel="stylesheet" href="<?php echo $GetStylesheetURL('/share/dist/styles.css'); ?>" />
	<script type="text/javascript" src="<?php echo $GetStylesheetURL('/themes/default/js/scripts.js'); ?>"></script>
	<link type="text/css" rel="stylesheet" href="<?php echo $GetStylesheetURL('/themes/default/css/styles.css'); ?>" />

	<!-- remote libraries -->
	<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,700;1,200;1,300;1,400;1,500;1,700&family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Share+Tech+Mono&family=Quicksand:wght@300;400;700&subset=latin-ext&display=swap" rel="stylesheet">
	<!-- <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Share+Tech+Mono&amp;subset=latin-ext" /> -->
	<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>

	<title><?php $Surface->Show('page-title') ?></title>
	<meta name="description" content="<?php $Surface->Show('Page.Desc') ?>" />
	<meta name="keywords" content="<?php $Surface->Show('Page.Keywords') ?>" />
	<meta name="author" content="<?php $Surface->Show('Page.Authour') ?>" />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="<?php $Surface->Show('Page.Title') ?>" />
	<meta name="twitter:creator" content="<?php $Surface->Show('Social.Authour') ?>" />
	<meta name="twitter:image" content="<?php $Surface->Show('Social.Image') ?>" />
	<meta name="twitter:domain" content="<?php $Printer($Router->GetDomain()) ?>" />
	<meta property="og:site_name" content="<?php $Printer(Nether\Option::Get('app-name')) ?>">
	<meta property="og:title" content="<?php $Surface->Show('Page.Title') ?>">
	<meta property="og:image" content="<?php $Surface->Show('Social.Image') ?>">


</head>
<body class="font-family-regular">
	<div id="Toaster" style="position:fixed;top:0px;right:0px;z-index:9001;"></div>

<?php $Surface->Area('design/header') ?>

<?php if($Route->Errors->Count()): ?>
<div class="ErrorTray">
<?php Theme::RenderInlineErrors($Route->Errors); ?>
</div>
<?php endif; ?>

<section>

<?php echo $Surface->Get('stdout') ?>

</section>

<?php $Surface->Area('design/footer') ?>

</body>
</html>