<?php

require_once('theme.php');

$GetStylesheetURL = function(String $URI):String {
	if(ENV\DEV)
	return "{$URI}.php";

	return $URI;
};

?>
<!doctype html>
<html>
<head>

	<title><?php $Surface->Show('page-title') ?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge" />
	<meta name="theme-color" content="#333" />

	<!-- local packages -->
	<link rel="icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<link rel="shortcut icon" href="/themes/default/gfx/icon-fav.png" type="image/png">
	<script type="text/javascript" src="<?php echo $GetStylesheetURL('/share/dist/scripts.js'); ?>"></script>
	<link type="text/css" rel="stylesheet" href="<?php echo $GetStylesheetURL('/share/dist/styles.css'); ?>" />
	<script type="text/javascript" src="<?php echo $GetStylesheetURL('/themes/default/js/scripts.js'); ?>"></script>
	<link type="text/css" rel="stylesheet" href="<?php echo $GetStylesheetURL('/themes/default/css/styles.css'); ?>" />

	<!-- remote libraries -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Share+Tech+Mono&amp;subset=latin-ext" />
	<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>

</head>
<body>

<?php $Surface->Area('design/header') ?>

<?php if($Route->Errors->Count()): ?>
<div class="ErrorTray">
<?php Theme::RenderInlineErrors($Route->Errors); ?>
</div>
<?php endif; ?>

<section>

<?php echo $Surface->Get('stdout') ?>

</section>

<footer>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-auto mb-4 mb-md-0">
				<code><?php Theme::RenderAppStats(); ?></code>
			</div>
			<div class="col-12 col-md mb-4 mb-md-0"></div>
			<div class="col-12 col-md-auto mb-4 mb-md-0">
				<a href="https://github.com/bobmagicii/atlantis" target="_blank"><i class="fa fa-github"></i> Github</a>
			</div>
		</div>
	</div>
</footer>

</body>
</html>