<div class="TextAlignCenter">
	<h3>Login</h3>
	<form method="post">
		<div class="PaddingVerticalBarely">
			<input type="text" name="Account" placeholder="Email..." />
		</div>
		<div class="PaddingVerticalBarely">
			<input type="password" name="Password" placeholder="Password..." />
		</div>
		<div class="PaddingVerticalBarely">
			<input type="submit" value="Log In" />
		</div>
	</form>
</div>