<div class="container pt-8 pb-8">
	<div class="row justify-content-center">
		<div class="col-12 col-sm-6 col-md-5">
			<h3 class="font-weight-bold text-uppercase mb-0">Log In</h3>
			<hr class="mt-2 mb-4" />
			<div class="mb-4">
				<div class="mb-2"><a href="<?php $Printer($Endpoint('Atlantis.Login.Auth.Github')) ?>" class="btn btn-dark btn-block text-left"><i class="fab fa-fw fa-github mr-2"></i> Log In With Github</a></div>
				<div class="mb-2"><a href="<?php $Printer($Endpoint('Atlantis.Login.Auth.Twitter')) ?>" class="btn btn-twitter btn-block text-left"><i class="fab fa-fw fa-twitter mr-2"></i> Log In With Twitter</a></div>
			</div>
			<div class="row align-items-center mb-4">
				<div class="col"><hr /></div>
				<div class="col-auto">OR</div>
				<div class="col"><hr /></div>
			</div>
			<form method="post">
				<div class="form-group mb-2">
					<input type="text" name="Account" class="form-control" placeholder="Email..." />
				</div>
				<div class="form-group mb-2">
					<input type="password" name="Password" class="form-control" placeholder="Password..." />
				</div>
				<div class="form-group mb-2">
					<input type="submit" class="btn btn-block btn-dark" value="Log In" />
				</div>
			</form>
		</div>
	</div>
</div>