<div class="TextAlignCenter">
	<h3>Login</h3>
	<form method="post">
		<div class="PaddingVerticalBarely" style="width:300px;margin:0px auto;">
			<input type="text" name="Account" class="WidthFull" placeholder="Email..." />
		</div>
		<div class="PaddingVerticalBarely" style="width:300px;margin:0px auto;">
			<input type="password" name="Password" class="WidthFull" placeholder="Password..." />
		</div>
		<div class="PaddingVerticalBarely">
			<input type="submit" value="Log In" />
		</div>
	</form>
</div>