<?php

$Pages = $Surface->Get('Pages');
header("Content-type: text/xml");

?>
<?xml version="1.0" encoding="UTF-8" ?>
<urlset
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<?php foreach($Pages as $Page): ?>
	<url>
		<loc><?php $Printer($Page->URL) ?></loc>
		<lastmod><?php $Printer($Page->Date) ?></lastmod>
		<priority><?php $Printer($Page->Priority) ?></priority>
	</url>
<?php endforeach; ?>
</urlset>
